baseURL = 'https://itszaim.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "anatole"
enableEmoji = true

[params]
title = "My Coding Journal"
author = "itszaim"
description = "Blogging away my coding journey"
